"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { createUserWithEmailAndPassword, sendEmailVerification, sendPasswordResetEmail, signInWithEmailAndPassword } from "firebase/auth";
import { firebaseAuth, firebaseConfigured } from "../lib/firebase";

export function AuthForm({ mode }: { mode: "login" | "signup" }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!firebaseAuth) return setMessage("Firebase is not configured for this deployment."); setBusy(true); setMessage(""); try { if (mode === "signup") { const credential = await createUserWithEmailAndPassword(firebaseAuth, email, password); await sendEmailVerification(credential.user); window.location.assign("/onboarding"); } else { const credential = await signInWithEmailAndPassword(firebaseAuth, email, password); window.location.assign(credential.user.emailVerified ? "/app/dashboard" : "/onboarding"); } } catch (error) { setMessage(error instanceof Error ? error.message : "Authentication could not be completed."); } finally { setBusy(false); } };
  const reset = async () => { if (!firebaseAuth || !email) return setMessage("Enter your email address first."); try { await sendPasswordResetEmail(firebaseAuth, email); setMessage("Password-reset email sent."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to send reset email."); } };
  return <form className="auth-card" onSubmit={submit}><p className="eyebrow">SECURE ACCESS</p><h1>{mode === "login" ? "Sign in to your workspace" : "Create your SIRALOOM account"}</h1><p>{mode === "login" ? "Use your laboratory-approved account." : "Your organization administrator will provision access after verification."}</p><label>Email<input type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Password<input type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} minLength={8} value={password} onChange={e => setPassword(e.target.value)} required /></label>{message && <p className="form-message" role="status">{message}</p>}<button className="button" disabled={busy || !firebaseConfigured}>{busy ? "Working…" : mode === "login" ? "Sign in" : "Create account"}</button>{mode === "login" ? <><button type="button" className="text-button" onClick={reset}>Reset password</button><p>New to SIRALOOM? <Link href="/signup">Create an account</Link></p></> : <p>Already have an account? <Link href="/login">Sign in</Link></p>}</form>;
}
