from typing import Protocol
from backend.app.domain.schemas import CanonicalVariant

class AnnotationProvider(Protocol):
    @property
    def provider_id(self) -> str: ...
    @property
    def provider_version(self) -> str: ...
    def capabilities(self) -> set[str]: ...
    def annotate(self, variants: list[CanonicalVariant], context: dict) -> list[dict]: ...
