class EntitlementPlan(StrEnum):
    TRIAL = "TRIAL"
    EVALUATION = "EVALUATION"
    PAID = "PAID"
    ENTERPRISE = "ENTERPRISE"
    ON_PREMISE = "ON_PREMISE"

class EntitlementStatus(StrEnum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    EXHAUSTED = "EXHAUSTED"
    CONVERTED = "CONVERTED"
    CANCELLED = "CANCELLED"

class ArtifactType(StrEnum):

class CaseStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    COMPLETE = "COMPLETE"
    ARCHIVED = "ARCHIVED"
    SPECIMEN_REGISTERED = "SPECIMEN_REGISTERED"
    ARTIFACT_UPLOADED = "ARTIFACT_UPLOADED"
    VALIDATING = "VALIDATING"
    READY_FOR_ANALYSIS = "READY_FOR_ANALYSIS"
    INVALID = "INVALID"

class AnalysisStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"
    BLOCKED = "BLOCKED"

class StepStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    RETRYING = "RETRYING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    BLOCKED = "BLOCKED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"

class ArtifactType(StrEnum):
    VCF = "VCF"
    NORMALIZED_VCF = "NORMALIZED_VCF"
    ANNOTATED_VCF = "ANNOTATED_VCF"
    JSON = "JSON"
    REPORT_PDF = "REPORT_PDF"
    AUDIT_PACKAGE = "AUDIT_PACKAGE"
    LOG = "LOG"
    VCF_INDEX_TBI = "VCF_INDEX_TBI"
    VCF_INDEX_CSI = "VCF_INDEX_CSI"

class ResourceStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    NOT_CONFIGURED = "NOT_CONFIGURED"
    NOT_AVAILABLE = "NOT_AVAILABLE"
    ACCESS_DENIED = "ACCESS_DENIED"
    QUERY_FAILED = "QUERY_FAILED"
    DISABLED = "DISABLED"
    VALIDATED = "VALIDATED"
    INVALID = "INVALID"

class Availability(StrEnum):
    AVAILABLE = "AVAILABLE"
    NOT_CONFIGURED = "NOT_CONFIGURED"
    NOT_AVAILABLE = "NOT_AVAILABLE"
    ACCESS_DENIED = "ACCESS_DENIED"
    QUERY_FAILED = "QUERY_FAILED"

class ReviewStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    IN_REVIEW = "IN_REVIEW"
    MORE_EVIDENCE = "MORE_EVIDENCE"
    COMPLETED = "COMPLETED"
    APPROVED = "APPROVED"

class Classification(StrEnum):
    PATHOGENIC = "PATHOGENIC"
    LIKELY_PATHOGENIC = "LIKELY_PATHOGENIC"
    VUS = "VUS"
    LIKELY_BENIGN = "LIKELY_BENIGN"
    BENIGN = "BENIGN"

class UserRole(StrEnum):
    ADMIN = "ADMIN"
    LAB_MANAGER = "LAB_MANAGER"
    ANALYST = "ANALYST"
    REVIEWER = "REVIEWER"
    MEDICAL_REVIEWER = "MEDICAL_REVIEWER"
    AUDITOR = "AUDITOR"
    READ_ONLY = "READ_ONLY"
