"""Organization-specific scientific resource execution planning.

The planner answers one question before a workflow step runs:

    Which resources that this organization has actually adopted can execute
    the capabilities required by this case?

Unregistered resources are not attempted. Missing optional resources are not
workflow failures. Required resources are only blocking when the workflow
actually needs that capability.

No user-facing "scientific limitation" is generated by this planner. It records
execution facts for provenance and downstream evidence availability.
"""
from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.orm import Session

from backend.app.domain.provider_registry import register_builtin_providers
from backend.app.domain.resource_capabilities import (
    CapabilityRequirement,
    ResourceCapability,
    ResourceExecutionAvailability,
    infer_capabilities,
    provider_allowed_in_deployment,
)
from backend.app.domain.resource_deployment import resolve_resource_deployment_policy
from backend.app.domain.resource_execution import ResourceExecutionError, resolve_resource_execution
from backend.app.infrastructure.db.models import (
    OrganizationResourceBinding,
    Resource,
)


@dataclass(frozen=True)
class PlannedResource:
    resource: Resource
    capability: ResourceCapability
    availability: ResourceExecutionAvailability
    provider_version: str | None = None
    reason_code: str | None = None


@dataclass(frozen=True)
class ResourceExecutionPlan:
    organization_id: UUID
    profile_type: str
    profile_version: str
    required: tuple[PlannedResource, ...]
    optional: tuple[PlannedResource, ...]
    unavailable_optional: tuple[PlannedResource, ...]
    unavailable_required: tuple[PlannedResource, ...]
    selected: tuple[PlannedResource, ...]

    @property
    def can_continue(self) -> bool:
        return not self.unavailable_required

    def for_capability(self, capability: ResourceCapability) -> tuple[PlannedResource, ...]:
        return tuple(item for item in self.selected if item.capability == capability)


def _bound_resources(db: Session, organization_id: UUID) -> list[Resource]:
    bindings = db.scalars(
        select(OrganizationResourceBinding)
        .where(OrganizationResourceBinding.organization_id == organization_id)
        .order_by(OrganizationResourceBinding.resource_name, OrganizationResourceBinding.provider)
    ).all()
    resources: list[Resource] = []
    for binding in bindings:
        resource = db.get(Resource, binding.resource_id)
        if resource is not None:
            resources.append(resource)
    return resources


def _trial_resources(db: Session) -> list[Resource]:
    return db.scalars(
        select(Resource)
        .where(
            Resource.organization_id.is_(None),
            Resource.status == "ACTIVE",
        )
        .order_by(Resource.name, Resource.provider, Resource.version),
    ).all()


def build_resource_execution_plan(
    db: Session,
    *,
    organization_id: UUID,
    requirements: tuple[CapabilityRequirement, ...],
) -> ResourceExecutionPlan:
    policy = resolve_resource_deployment_policy(db, organization_id=organization_id)
    registry = register_builtin_providers()

    candidates = _trial_resources(db) if policy.is_trial else _bound_resources(db, organization_id)

    required: list[PlannedResource] = []
    optional: list[PlannedResource] = []
    unavailable_optional: list[PlannedResource] = []
    unavailable_required: list[PlannedResource] = []
    selected: list[PlannedResource] = []

    for requirement in requirements:
        matches: list[PlannedResource] = []

        for resource in candidates:
            capabilities = infer_capabilities(
                resource_type=resource.resource_type,
                provider=resource.provider,
                metadata=resource.metadata_json,
            )
            if requirement.capability not in capabilities:
                continue

            if not provider_allowed_in_deployment(
                resource.provider,
                is_trial=policy.is_trial,
            ):
                continue

            try:
                execution = resolve_resource_execution(db, resource=resource)
            except ResourceExecutionError:
                continue

            implementation = registry.resolve(
                provider_id=execution.contract.provider_id,
                provider_version=execution.contract.provider_version,
            )
            if implementation is None:
                matches.append(
                    PlannedResource(
                        resource=resource,
                        capability=requirement.capability,
                        availability=ResourceExecutionAvailability.PROVIDER_NOT_IMPLEMENTED,
                        provider_version=execution.contract.provider_version,
                        reason_code="PROVIDER_IMPLEMENTATION_MISSING",
                    )
                )
                continue

            descriptor = implementation.descriptor
            if (
                descriptor.supported_builds
                and resource.genome_build
                and resource.genome_build.upper() not in descriptor.supported_builds
            ):
                matches.append(
                    PlannedResource(
                        resource=resource,
                        capability=requirement.capability,
                        availability=ResourceExecutionAvailability.INCOMPATIBLE,
                        provider_version=execution.contract.provider_version,
                        reason_code="BUILD_NOT_SUPPORTED",
                    )
                )
                continue

            matches.append(
                PlannedResource(
                    resource=resource,
                    capability=requirement.capability,
                    availability=ResourceExecutionAvailability.AVAILABLE,
                    provider_version=execution.contract.provider_version,
                )
            )

        available = [item for item in matches if item.availability == ResourceExecutionAvailability.AVAILABLE]
        if available:
            selected.extend(available)
            target = required if requirement.required else optional
            target.extend(available)
        else:
            unavailable = matches or []
            if requirement.required:
                unavailable_required.extend(unavailable)
            else:
                unavailable_optional.extend(unavailable)

    # A trial catalog can contain many globally managed resources. Only the
    # capability-specific selected resources are executable; there is no
    # "execute every resource in the catalog" behavior.
    return ResourceExecutionPlan(
        organization_id=organization_id,
        profile_type=policy.profile_type,
        profile_version=policy.profile_version,
        required=tuple(required),
        optional=tuple(optional),
        unavailable_optional=tuple(unavailable_optional),
        unavailable_required=tuple(unavailable_required),
        selected=tuple(selected),
    )
